services:
  profile:
    build:
      context: .
      dockerfile: modules/profile/cmd/profile/Dockerfile
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
      RESUME_PATH: ./assets/hieu_profile.md
